"""med04_add_missing_indexes

Revision ID: caca10153183
Revises: 006_add_image_url
Create Date: 2026-04-09 14:23:07.112133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caca10153183'
down_revision: Union[str, None] = '006_add_image_url'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_br_broadcast_status', 'broadcast_recipients', ['broadcast_id', 'status'], unique=False)
    op.create_index('ix_br_provider_message_id', 'broadcast_recipients', ['provider_message_id'], unique=False)
    op.drop_index('ix_conversations_embedding', table_name='conversations', postgresql_using='hnsw')
    op.create_index('ix_conversations_created_at', 'conversations', ['created_at'], unique=False)
    op.create_index('ix_conversations_flagged_alert', 'conversations', ['flagged', 'alert_sent'], unique=False)
    op.create_index('ix_offers_is_active', 'offers', ['is_active'], unique=False)
    op.create_index('ix_offers_valid_until', 'offers', ['valid_until'], unique=False)
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_is_active', table_name='products')
    op.drop_index('ix_offers_valid_until', table_name='offers')
    op.drop_index('ix_offers_is_active', table_name='offers')
    op.drop_index('ix_conversations_flagged_alert', table_name='conversations')
    op.drop_index('ix_conversations_created_at', table_name='conversations')
    op.create_index('ix_conversations_embedding', 'conversations', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_index('ix_br_provider_message_id', table_name='broadcast_recipients')
    op.drop_index('ix_br_broadcast_status', table_name='broadcast_recipients')
    # ### end Alembic commands ###
